spring:
  profiles:
    active: docker
  application:
    name: microservicecloud-eureka

server:
  port: ${port}

eureka:
  instance:
    hostname: ${eureka_hostname}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
  client:
#     register-with-eureka: false     #false表示不向注册中心注册自己。
#     fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: ${eureka_service_url}
