server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: microservicecloud-consumer

feign:
 hystrix:
   enabled: true

eureka:
 instance:
   instance-id: ${spring.application.name}${server.port}
   prefer-ip-address: true     #访问路径可以显示IP地址
 client: #客户端注册进eureka服务列表内
   service-url:
     defaultZone: http://eureka7001.com:7001/eureka/